name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  node-tests:
    strategy:
      fail-fast: false
      matrix:
        node_version: [ 16, 18, 20 ]
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm install -g npm@9.9.4

      - name: Update rush shrinkwrap dependencies (for different node versions - node 20 change the hash algorithm)
        run: node common/scripts/install-run-rush.js update --full --recheck
      - run: npm install rollup -g
      - name: Bootstrap
        run: npm install
      # - run: node common/scripts/install-run-rush.js check
      - run: node common/scripts/install-run-rush.js update --full --recheck

      - name: Build 🔧
        run: |
          npm run rebuild --verbose

      - name: Unit tests
        run: |
          # TODO(legendecas): webpack https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
          if [ "${{ matrix.node_version }}" = "18" ]; then
            export NODE_OPTIONS=--openssl-legacy-provider
          fi
          npm run test --verbose

  node-windows-tests:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        node_version: [ 18, 20 ]

    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm install -g npm@9.9.4
  
      - name: Update rush shrinkwrap dependencies (for different node versions - node 20 change the hash algorithm)
        run: node common/scripts/install-run-rush.js update --full --recheck
      - run: npm install rollup -g
      - name: Bootstrap
        run: npm install
      # - run: node common/scripts/install-run-rush.js check
      - run: node common/scripts/install-run-rush.js update --full --recheck

      - name: Build 🔧
        run: |
          npm run rebuild --verbose

      - name: Unit tests
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm run test --verbose
